export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_ERROR = "GOOGLE_LOGIN_ERROR";
export const GOOGLE_LOGOUT_SUCCESS = "GOOGLE_LOGOUT_SUCCESS";
export const GOOGLE_LOGOUT_ERROR = "GOOGLE_LOGOUT_ERROR";
export const AUTH_STATE_SET = "AUTH_STATE_SET";
