export const LOADING = "LOADING";
export const LOADED = "LOADED";
export const SET_DARK_THEME = "SET_DARK_THEME";
export const SET_LIGHT_THEME = "SET_LIGHT_THEME";
export const SET_CREATE_NOTE_CON_ACTIVE = "SET_CREATE_NOTE_CON_ACTIVE";
export const RESET_CREATE_NOTE_CON_ACTIVE = "RESET_CREATE_NOTE_CON_ACTIVE";
export const SET_BACKGROUND_PALETTE_ACTIVE = "SET_BACKGROUND_PALETTE_ACTIVE";
export const RESET_BACKGROUND_PALETTE_ACTIVE =
  "RESET_BACKGROUND_PALETTE_ACTIVE";
